### ISSUE TITLE
Merge idc2r.py and idb2r2.py

### ISSUE THREAD

**Issue by Maijin** [radare/radare2ida#10]
Merge idc2r.py and idb2r2.py

**Comment by ITAYC0HEN** [comment]
On it. Will be ready next week~

**Comment by XVilka** [comment]
@ITAYC0HEN next week is passed, just FYI

**Comment by XVilka** [comment]
@ITAYC0HEN can you please check it?

**Comment by ITAYC0HEN** [comment]
Done.
