### ISSUE TITLE
Feature request: IDA dbg server compatibility with r2

### ISSUE THREAD

**Issue by securisec** [radare/radare2ida#6]
IDA provides various debug servers which works over tcp. Requesting IDA compatibility with these dbg servers. The following are the list of servers, but the windows servers would be the immediate request so that a windows program can be debugged using the latest radare2 (without going through the complexity of building r2 for windows)
```
android_server
android_server64
android_server_nonpie
android_x64_server
android_x86_server
armlinux_server
armuclinux_server
dbghelp.dll
ida_kdstub.dll
linux_server
linux_server64
mac_server
mac_server64
symsrv.dll
** win32_remote.exe
** win64_remote64.exe
wince_remote_arm.dll
wince_remote_tcp_arm.exe
```

Msft offers free to use VMs that can be used to test against. https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by XVilka** [comment]
I think this belongs to the radare2 or radare2-extras instead of radare2ida.

**Comment by radare** [comment]
Well if it is not ida specific shouldnot be here

**Comment by securisec** [comment]
This is more of a wish list for more debugger integration into r2. Seeing that the ida debuggers work over tcp already, I figured I would put it here. Feel free to move it around as best, or close the request if it doesn't apply.

**Comment by Maijin** [comment]
Yep radare2-extras.
